baseurl = "https://briancoia.com/"
title = "Brian Coia"
copyright = "(c) 2016 Brian Coia"
languageCode = "en-us"
disqusShortname = "bcoia" # Optional, enable Disqus integration
metaDataFormat = "yaml"
theme = "hyde-y"

# Pagination
paginate = 10
paginatePath = "page"

[author]
    name = "Brian Coia"
    email = "brian@briancoia.com"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    project = "/project/:slug/"

[taxonomies]
    tag = "tags"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Brian Coia"
    topline = "Web developer and giant nerd"
    #footline = ""

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "false"

    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Brian Coia, web developer and giant nerd"
    defaultKeywords = "brian,coia,web,developer"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = true

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Web developer and giant nerd"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = ""
    gravatarHash = "779fbbf06b0fe9ae605e266227387137"

    # Sidebar social links.
    github = "bcoia" # Your Github profile ID
    linkedin = "bcoia" # Your LinkedIn profile ID (from public URL)
    googleplus = "briancoia" # Your Google+ profile ID
    twitter = "bcoia" # Your Twitter profile ID

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
