baseurl = "https://briancoia.com/"
title = "Brian Coia"
copyright = "Brian Coia"
languageCode = "en-us"
metaDataFormat = "yaml"
theme = "ghostwriter"

disqusShortname = "bcoia"
googleAnalytics = "UA-29421156-1"
gravatarHash = "779fbbf06b0fe9ae605e266227387137"

[Author]
    name = "Brian Coia"
    email = "brian@briancoia.com"
    profile = "https://google.com/+briancoia"

[Permalinks]
    page = "/:slug/"
    post = "/:year/:month/:day/:slug/"
    project = "/project/:slug/"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Brian Coia"
    description = "Web developer, button pressing enthusiast"
    github = "https://github.com/bcoia"
    linkedin = "https://linkedin.com/in/bcoia/"
    gplus = "https://google.com/+briancoia"
    twitter = "https://twitter.com/bcoia"
    stackoverflow = "http://stackoverflow.com/users/1297082/bcoia"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
