baseurl = "https://briancoia.com/"
title = "Brian Coia"
copyright = "Brian Coia"
languageCode = "en-us"
theme = "ghostwriter"

disqusShortname = "briancoia"
googleAnalytics = "UA-29421156-1"
gravatarHash = "779fbbf06b0fe9ae605e266227387137"

[author]
    name = "Brian Coia"
    email = "brian@briancoia.com"
    profile = "https://google.com/+briancoia"

[permalinks]
    page = "/:slug/"
    post = "/:year/:month/:day/:slug/"
    project = "/project/:slug/"

[taxonomies]
    tag = "tags"
    project = "projects"

[params]
    intro = true
    headline = "Brian Coia"
    description = "Web developer, button pressing enthusiast"
    footer = "I write code for <a href='http://www.fangamer.com'>Fangamer</a> and manage community game servers at <a href='https://redco.in'>Red Coin</a>. You can reach me on <a href='https://twitter.com/redcoin'>Twitter</a>, or via email at<br/><em>my first name</em> at <em>this domain</em>."
    github = "https://github.com/bcoia"
    linkedin = "https://linkedin.com/in/bcoia/"
    gplus = "https://google.com/+briancoia"
    twitter = "https://twitter.com/redcoin"
    stackoverflow = "http://stackoverflow.com/users/1297082/bcoia"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
